spring.application.name=1er-despliegue
server.port=${PORT:8080}

spring.r2dbc.url=r2dbc:postgresql://${PGHOST:localhost}:${PGPORT:5432}/${PGDATABASE:tasksdb}
spring.r2dbc.username=${PGUSER:postgres}
spring.r2dbc.password=${PGPASSWORD:postgres}
spring.r2dbc.pool.enabled=true
spring.r2dbc.pool.initial-size=2
spring.r2dbc.pool.max-size=10

spring.flyway.enabled=true
spring.flyway.url=jdbc:postgresql://${PGHOST:localhost}:${PGPORT:5432}/${PGDATABASE:tasksdb}
spring.flyway.user=${PGUSER:postgres}
spring.flyway.password=${PGPASSWORD:postgres}
spring.flyway.locations=classpath:db/migration

management.endpoints.web.exposure.include=health,info
